spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?useSSL=false&serverTimezone=UTC
    username: root
    password: Summer1$
    driver-class-name: com.mysql.cj.jdbc.Driver # changed to driver-class-name
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # Typically, use 'update' for development instead of 'create'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE  # To log parameter values
    springframework:
      http: DEBUG

weather:
  api:
    key: b3de109dfca2fabd39801c5170a75703
    baseUrl: https://api.openweathermap.org/data/2.5/weather

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: your-secret-key-here
    expiration: 86400000 # 24 hours
